global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 5s

  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: "http://prometheus:9090/api/v1/write"

remote_read:
  - url: "http://prometheus:9090/api/v1/read"

storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 50GB
    wal:
      retention:
        time: 12h

# Alert Rules
alerting_rules:
  groups:
    - name: example
      rules:
        - alert: HighRequestLatency
          expr: job:request_latency_seconds:mean5m{job="backend"} > 0.5
          for: 10m
          labels:
            severity: page
          annotations:
            summary: High request latency on {{ $labels.instance }}
            description: {{ $labels.instance }} has a request latency above 0.5s (current value: {{ $value }}s)

        - alert: HighErrorRate
          expr: job:request_errors:rate5m{job="backend"} > 0.05
          for: 10m
          labels:
            severity: page
          annotations:
            summary: High error rate on {{ $labels.instance }}
            description: {{ $labels.instance }} has a high error rate (current value: {{ $value }})

        - alert: HighCPUUsage
          expr: instance:node_cpu_usage:rate5m > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage on {{ $labels.instance }}
            description: {{ $labels.instance }} has high CPU usage (current value: {{ $value }})

        - alert: HighMemoryUsage
          expr: instance:node_memory_usage:rate5m > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High memory usage on {{ $labels.instance }}
            description: {{ $labels.instance }} has high memory usage (current value: {{ $value }})

        - alert: DiskSpaceRunningOut
          expr: instance:node_filesystem_free:bytes < 10737418240
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Disk space running out on {{ $labels.instance }}
            description: {{ $labels.instance }} has less than 10GB disk space remaining

# Recording Rules
recording_rules:
  groups:
    - name: example
      rules:
        - record: job:request_latency_seconds:mean5m
          expr: rate(request_latency_seconds_sum[5m]) / rate(request_latency_seconds_count[5m])

        - record: job:request_errors:rate5m
          expr: rate(request_errors_total[5m])

        - record: instance:node_cpu_usage:rate5m
          expr: 1 - avg without(cpu)(rate(node_cpu_seconds_total{mode="idle"}[5m]))

        - record: instance:node_memory_usage:rate5m
          expr: 1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes

        - record: instance:node_filesystem_free:bytes
          expr: node_filesystem_free_bytes{mountpoint="/"}